spring:
  datasource:
    url: jdbc:postgresql://postgresql:5432/postgres
    username: postgres
    password: root
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update